#pragma once

#include "Game.h"

const std::string EGGBIRD_IMG = "../Image/Animation/eggbird.png";
const int FRAMES_EGGBIRD = 8;
const int EGGBIRD_W = 560;
const int EGGBIRD_H = 420;
const int EGGBIRD_REAL_W = EGGBIRD_W/EGGBIRD_SCALE;
const int EGGBIRD_REAL_H = EGGBIRD_H/EGGBIRD_SCALE;
const int RANGE_FRAME_EGGBIRD = 800+560;
const int CLIPS_EGGBIRD[FRAMES_EGGBIRD][4] = {
    {405+RANGE_FRAME_EGGBIRD*0, 50, 560, 420},
    {405+RANGE_FRAME_EGGBIRD*1, 50, 560, 420},
    {405+RANGE_FRAME_EGGBIRD*2, 50, 560, 420},
    {405+RANGE_FRAME_EGGBIRD*3, 50, 560, 420},
    {405+RANGE_FRAME_EGGBIRD*4, 50, 560, 420},
    {405+RANGE_FRAME_EGGBIRD*5, 50, 560, 420},
    {405+RANGE_FRAME_EGGBIRD*6, 50, 560, 420},
    {405+RANGE_FRAME_EGGBIRD*7, 50, 560, 420},
};

const std::string UNICORNBIRD_IMG = "../Image/Animation/unicornbird.png";
const int FRAMES_UNICORNBIRD = 8;
const int UNICORNBIRD_W = 450;
const int UNICORNBIRD_H = 575;
const int UNICORNBIRD_REAL_W = UNICORNBIRD_W/UNICORNBIRD_SCALE;
const int UNICORNBIRD_REAL_H = UNICORNBIRD_H/UNICORNBIRD_SCALE;
const int RANGE_FRAME_UNICORNBIRD = 1120;
const int CLIPS_UNICORNBIRD[FRAMES_UNICORNBIRD][4] = {
    {336+RANGE_FRAME_UNICORNBIRD*0, 144, 450, 575},
    {336+RANGE_FRAME_UNICORNBIRD*1, 144, 450, 575},
    {336+RANGE_FRAME_UNICORNBIRD*2, 144, 450, 575},
    {336+RANGE_FRAME_UNICORNBIRD*3, 144, 450, 575},
    {336+RANGE_FRAME_UNICORNBIRD*4, 144, 450, 575},
    {336+RANGE_FRAME_UNICORNBIRD*5, 144, 450, 575},
    {336+RANGE_FRAME_UNICORNBIRD*6, 144, 450, 575},
    {336+RANGE_FRAME_UNICORNBIRD*7, 144, 450, 575},
};



const std::string EAGLE_IMG = "../Image/Animation/eagle.png";
const int EAGLE_SCALE = 1;
const int EAGLE_W = 121;
const int EAGLE_H = 85;
const int EAGLE_REAL_W = EAGLE_W/EAGLE_SCALE;
const int EAGLE_REAL_H = EAGLE_H/EAGLE_SCALE;
const int EAGLE_0 = 117;
const int EAGLE_1 = 201;
const int EAGLE_2 = 292;
const int EAGLE_3 = 383;
const int EAGLE_4 = 471;
const int EAGLE_5 = 563;
const int EAGLE_6 = 648;
const int EAGLE_7 = 738;


const int FRAMES_EAGLE_FLYING = 8;
const int RANGE_FRAME_EAGLE_FLYING = 134;
const int CLIPS_EAGLE_FLYING[FRAMES_EAGLE_FLYING][4] = {
    {RANGE_FRAME_EAGLE_FLYING, EAGLE_0, EAGLE_W, EAGLE_H},
    {RANGE_FRAME_EAGLE_FLYING, EAGLE_1, EAGLE_W, EAGLE_H},
    {RANGE_FRAME_EAGLE_FLYING, EAGLE_2, EAGLE_W, EAGLE_H},
    {RANGE_FRAME_EAGLE_FLYING, EAGLE_3, EAGLE_W, EAGLE_H},
    {RANGE_FRAME_EAGLE_FLYING, EAGLE_4, EAGLE_W, EAGLE_H},
    {RANGE_FRAME_EAGLE_FLYING, EAGLE_5, EAGLE_W, EAGLE_H},
    {RANGE_FRAME_EAGLE_FLYING, EAGLE_6, EAGLE_W, EAGLE_H},
    {RANGE_FRAME_EAGLE_FLYING, EAGLE_7, EAGLE_W, EAGLE_H},
};

const int FRAMES_EAGLE_GOT_HIT = 8;
const int RANGE_FRAME_EAGLE_GOT_HIT = 274;
const int CLIPS_EAGLE_GOT_HIT[FRAMES_EAGLE_GOT_HIT][4] = {
    {RANGE_FRAME_EAGLE_GOT_HIT, EAGLE_0, EAGLE_W, EAGLE_H},
    {RANGE_FRAME_EAGLE_GOT_HIT, EAGLE_1, EAGLE_W, EAGLE_H},
    {RANGE_FRAME_EAGLE_GOT_HIT, EAGLE_2, EAGLE_W, EAGLE_H},
    {RANGE_FRAME_EAGLE_GOT_HIT, EAGLE_3, EAGLE_W, EAGLE_H},
    {RANGE_FRAME_EAGLE_GOT_HIT, EAGLE_4, EAGLE_W, EAGLE_H},
    {RANGE_FRAME_EAGLE_GOT_HIT, EAGLE_5, EAGLE_W, EAGLE_H},
    {RANGE_FRAME_EAGLE_GOT_HIT, EAGLE_6, EAGLE_W, EAGLE_H},
    {RANGE_FRAME_EAGLE_GOT_HIT, EAGLE_7, EAGLE_W, EAGLE_H},
};

const int FRAMES_EAGLE_SHOT = 3;
const int RANGE_FRAME_EAGLE_SHOT = 426;
const int CLIPS_EAGLE_SHOT[FRAMES_EAGLE_SHOT][4] = {
    {RANGE_FRAME_EAGLE_SHOT, EAGLE_0, EAGLE_W, EAGLE_H},
    {RANGE_FRAME_EAGLE_SHOT, EAGLE_1, EAGLE_W, EAGLE_H},
    {RANGE_FRAME_EAGLE_SHOT, EAGLE_2, EAGLE_W, EAGLE_H},
};

const int FRAMES_EAGLE_RAM = 8;
const int RANGE_FRAME_EAGLE_RAM = 574;
const int CLIPS_EAGLE_RAM[FRAMES_EAGLE_RAM][4] = {
    {RANGE_FRAME_EAGLE_RAM, EAGLE_0, EAGLE_W, EAGLE_H},
    {RANGE_FRAME_EAGLE_RAM, EAGLE_1, EAGLE_W, EAGLE_H},
    {RANGE_FRAME_EAGLE_RAM, EAGLE_2, EAGLE_W, EAGLE_H},
    {RANGE_FRAME_EAGLE_RAM, EAGLE_3, EAGLE_W, EAGLE_H},
    {RANGE_FRAME_EAGLE_RAM, EAGLE_4, EAGLE_W, EAGLE_H},
    {RANGE_FRAME_EAGLE_RAM, EAGLE_5, EAGLE_W, EAGLE_H},
    {RANGE_FRAME_EAGLE_RAM, EAGLE_6, EAGLE_W, EAGLE_H},
    {RANGE_FRAME_EAGLE_RAM, EAGLE_7, EAGLE_W, EAGLE_H},
};

const int FRAMES_EAGLE_DEAD = 8;
const int RANGE_FRAME_EAGLE_DEAD = 723;
const int CLIPS_EAGLE_DEAD[FRAMES_EAGLE_DEAD][4] = {
    {RANGE_FRAME_EAGLE_DEAD, EAGLE_0, EAGLE_W, EAGLE_H},
    {RANGE_FRAME_EAGLE_DEAD, EAGLE_1, EAGLE_W, EAGLE_H},
    {RANGE_FRAME_EAGLE_DEAD, EAGLE_2, EAGLE_W, EAGLE_H},
    {RANGE_FRAME_EAGLE_DEAD, EAGLE_3, EAGLE_W, EAGLE_H},
    {RANGE_FRAME_EAGLE_DEAD, EAGLE_4, EAGLE_W, EAGLE_H},
    {RANGE_FRAME_EAGLE_DEAD, EAGLE_5, EAGLE_W, EAGLE_H},
    {RANGE_FRAME_EAGLE_DEAD, EAGLE_6, EAGLE_W, EAGLE_H},
    {RANGE_FRAME_EAGLE_DEAD, EAGLE_7, EAGLE_W, EAGLE_H},
};

const int FRAMES_EAGLE_HENSHIN = 8;
const int RANGE_FRAME_EAGLE_HENSHIN = 872;
const int CLIPS_EAGLE_HENSHIN[FRAMES_EAGLE_HENSHIN][4] = {
    {RANGE_FRAME_EAGLE_HENSHIN, EAGLE_0, EAGLE_W, EAGLE_H},
    {RANGE_FRAME_EAGLE_HENSHIN, EAGLE_1, EAGLE_W, EAGLE_H},
    {RANGE_FRAME_EAGLE_HENSHIN, EAGLE_2, EAGLE_W, EAGLE_H},
    {RANGE_FRAME_EAGLE_HENSHIN, EAGLE_3, EAGLE_W, EAGLE_H},
    {RANGE_FRAME_EAGLE_HENSHIN, EAGLE_4, EAGLE_W, EAGLE_H},
    {RANGE_FRAME_EAGLE_HENSHIN, EAGLE_5, EAGLE_W, EAGLE_H},
    {RANGE_FRAME_EAGLE_HENSHIN, EAGLE_6, EAGLE_W, EAGLE_H},
    {RANGE_FRAME_EAGLE_HENSHIN, EAGLE_7, EAGLE_W, EAGLE_H},
};

const int FRAMES_EAGLE_HENSHIN_SHOT = 3;
const int RANGE_FRAME_EAGLE_HENSHIN_SHOT = 1018;
const int CLIPS_EAGLE_HENSHIN_SHOT[FRAMES_EAGLE_HENSHIN_SHOT][4] = {
    {RANGE_FRAME_EAGLE_HENSHIN_SHOT, EAGLE_0, EAGLE_W, EAGLE_H},
    {RANGE_FRAME_EAGLE_HENSHIN_SHOT, EAGLE_1, EAGLE_W, EAGLE_H},
    {RANGE_FRAME_EAGLE_HENSHIN_SHOT, EAGLE_2, EAGLE_W, EAGLE_H},
};

const std::string COLLAPSION_BY_EAGLE_IMG = "../Image/Animation/explosion_eagle.png";
const int FRAMES_COLLAPSION_BY_EAGLE = 8;
const int COLLAPSION_BY_EAGLE_W = 224;
const int COLLAPSION_BY_EAGLE_H = 224;
const int COLLAPSION_BY_EAGLE_REAL_W = COLLAPSION_BY_EAGLE_W/COLLAPSION_BY_EAGLE_SCALE;
const int COLLAPSION_BY_EAGLE_REAL_H = COLLAPSION_BY_EAGLE_H/COLLAPSION_BY_EAGLE_SCALE;
const int RANGE_FRAME_COLLAPSION_BY_EAGLE = 224;
const int CLIPS_COLLAPSION_BY_EAGLE[FRAMES_COLLAPSION_BY_EAGLE][4] = {
    {RANGE_FRAME_COLLAPSION_BY_EAGLE*0, 0, 224, 224},
    {RANGE_FRAME_COLLAPSION_BY_EAGLE*1, 0, 224, 224},
    {RANGE_FRAME_COLLAPSION_BY_EAGLE*2, 0, 224, 224},
    {RANGE_FRAME_COLLAPSION_BY_EAGLE*3, 0, 224, 224},
    {RANGE_FRAME_COLLAPSION_BY_EAGLE*4, 0, 224, 224},
    {RANGE_FRAME_COLLAPSION_BY_EAGLE*5, 0, 224, 224},
    {RANGE_FRAME_COLLAPSION_BY_EAGLE*6, 0, 224, 224},
    {RANGE_FRAME_COLLAPSION_BY_EAGLE*7, 0, 224, 224},
};


const std::string CHICKEN_IMG = "../Image/Animation/chicken.png";
const int CHICKEN_SCALE = 1;
const int CHICKEN_W = 113;
const int CHICKEN_H = 85;
const int CHICKEN_REAL_W = CHICKEN_W/CHICKEN_SCALE;
const int CHICKEN_REAL_H = CHICKEN_H/CHICKEN_SCALE;
const int CHICKEN_0 = 217;
const int CHICKEN_1 = 306;
const int CHICKEN_2 = 394;
const int CHICKEN_3 = 485;
const int CHICKEN_4 = 573;
const int CHICKEN_5 = 664;
const int CHICKEN_6 = 753;
const int CHICKEN_7 = 843;

const int FRAMES_CHICKEN_FLYING = 8;
const int RANGE_FRAME_CHICKEN_FLYING = 203;
const int CLIPS_CHICKEN_FLYING[FRAMES_CHICKEN_FLYING][4] = {
    {RANGE_FRAME_CHICKEN_FLYING, CHICKEN_0, CHICKEN_W, CHICKEN_H},
    {RANGE_FRAME_CHICKEN_FLYING, CHICKEN_1, CHICKEN_W, CHICKEN_H},
    {RANGE_FRAME_CHICKEN_FLYING, CHICKEN_2, CHICKEN_W, CHICKEN_H},
    {RANGE_FRAME_CHICKEN_FLYING, CHICKEN_3, CHICKEN_W, CHICKEN_H},
    {RANGE_FRAME_CHICKEN_FLYING, CHICKEN_4, CHICKEN_W, CHICKEN_H},
    {RANGE_FRAME_CHICKEN_FLYING, CHICKEN_5, CHICKEN_W, CHICKEN_H},
    {RANGE_FRAME_CHICKEN_FLYING, CHICKEN_6, CHICKEN_W, CHICKEN_H},
    {RANGE_FRAME_CHICKEN_FLYING, CHICKEN_7, CHICKEN_W, CHICKEN_H},
};

const int FRAMES_CHICKEN_GOT_HIT = 8;
const int RANGE_FRAME_CHICKEN_GOT_HIT = 355;
const int CLIPS_CHICKEN_GOT_HIT[FRAMES_CHICKEN_GOT_HIT][4] = {
    {RANGE_FRAME_CHICKEN_GOT_HIT, CHICKEN_0, CHICKEN_W, CHICKEN_H},
    {RANGE_FRAME_CHICKEN_GOT_HIT, CHICKEN_1, CHICKEN_W, CHICKEN_H},
    {RANGE_FRAME_CHICKEN_GOT_HIT, CHICKEN_2, CHICKEN_W, CHICKEN_H},
    {RANGE_FRAME_CHICKEN_GOT_HIT, CHICKEN_3, CHICKEN_W, CHICKEN_H},
    {RANGE_FRAME_CHICKEN_GOT_HIT, CHICKEN_4, CHICKEN_W, CHICKEN_H},
    {RANGE_FRAME_CHICKEN_GOT_HIT, CHICKEN_5, CHICKEN_W, CHICKEN_H},
    {RANGE_FRAME_CHICKEN_GOT_HIT, CHICKEN_6, CHICKEN_W, CHICKEN_H},
    {RANGE_FRAME_CHICKEN_GOT_HIT, CHICKEN_7, CHICKEN_W, CHICKEN_H},
};

const int FRAMES_CHICKEN_SHOT = 3;
const int RANGE_FRAME_CHICKEN_SHOT = 505;
const int CLIPS_CHICKEN_SHOT[FRAMES_CHICKEN_SHOT][4] = {
    {RANGE_FRAME_CHICKEN_SHOT, CHICKEN_0, CHICKEN_W, CHICKEN_H},
    {RANGE_FRAME_CHICKEN_SHOT, CHICKEN_1, CHICKEN_W, CHICKEN_H},
    {RANGE_FRAME_CHICKEN_SHOT, CHICKEN_2, CHICKEN_W, CHICKEN_H},
};

const int FRAMES_CHICKEN_RAM = 8;
const int RANGE_FRAME_CHICKEN_RAM = 655;
const int CLIPS_CHICKEN_RAM[FRAMES_CHICKEN_RAM][4] = {
    {RANGE_FRAME_CHICKEN_RAM, CHICKEN_0, CHICKEN_W, CHICKEN_H},
    {RANGE_FRAME_CHICKEN_RAM, CHICKEN_1, CHICKEN_W, CHICKEN_H},
    {RANGE_FRAME_CHICKEN_RAM, CHICKEN_2, CHICKEN_W, CHICKEN_H},
    {RANGE_FRAME_CHICKEN_RAM, CHICKEN_3, CHICKEN_W, CHICKEN_H},
    {RANGE_FRAME_CHICKEN_RAM, CHICKEN_4, CHICKEN_W, CHICKEN_H},
    {RANGE_FRAME_CHICKEN_RAM, CHICKEN_5, CHICKEN_W, CHICKEN_H},
    {RANGE_FRAME_CHICKEN_RAM, CHICKEN_6, CHICKEN_W, CHICKEN_H},
    {RANGE_FRAME_CHICKEN_RAM, CHICKEN_7, CHICKEN_W, CHICKEN_H},
};

const int FRAMES_CHICKEN_DEAD = 8;
const int RANGE_FRAME_CHICKEN_DEAD = 804;
const int CLIPS_CHICKEN_DEAD[FRAMES_CHICKEN_DEAD][4] = {
    {RANGE_FRAME_CHICKEN_DEAD, CHICKEN_0, CHICKEN_W, CHICKEN_H},
    {RANGE_FRAME_CHICKEN_DEAD, CHICKEN_1, CHICKEN_W, CHICKEN_H},
    {RANGE_FRAME_CHICKEN_DEAD, CHICKEN_2, CHICKEN_W, CHICKEN_H},
    {RANGE_FRAME_CHICKEN_DEAD, CHICKEN_3, CHICKEN_W, CHICKEN_H},
    {RANGE_FRAME_CHICKEN_DEAD, CHICKEN_4, CHICKEN_W, CHICKEN_H},
    {RANGE_FRAME_CHICKEN_DEAD, CHICKEN_5, CHICKEN_W, CHICKEN_H},
    {RANGE_FRAME_CHICKEN_DEAD, CHICKEN_6, CHICKEN_W, CHICKEN_H},
    {RANGE_FRAME_CHICKEN_DEAD, CHICKEN_7, CHICKEN_W, CHICKEN_H},
};

const int FRAMES_CHICKEN_HENSHIN = 8;
const int RANGE_FRAME_CHICKEN_HENSHIN = 957;
const int CLIPS_CHICKEN_HENSHIN[FRAMES_CHICKEN_HENSHIN][4] = {
    {RANGE_FRAME_CHICKEN_HENSHIN, CHICKEN_0, CHICKEN_W, CHICKEN_H},
    {RANGE_FRAME_CHICKEN_HENSHIN, CHICKEN_1, CHICKEN_W, CHICKEN_H},
    {RANGE_FRAME_CHICKEN_HENSHIN, CHICKEN_2, CHICKEN_W, CHICKEN_H},
    {RANGE_FRAME_CHICKEN_HENSHIN, CHICKEN_3, CHICKEN_W, CHICKEN_H},
    {RANGE_FRAME_CHICKEN_HENSHIN, CHICKEN_4, CHICKEN_W, CHICKEN_H},
    {RANGE_FRAME_CHICKEN_HENSHIN, CHICKEN_5, CHICKEN_W, CHICKEN_H},
    {RANGE_FRAME_CHICKEN_HENSHIN, CHICKEN_6, CHICKEN_W, CHICKEN_H},
    {RANGE_FRAME_CHICKEN_HENSHIN, CHICKEN_7, CHICKEN_W, CHICKEN_H},
};

const int FRAMES_CHICKEN_HENSHIN_SHOT = 3;
const int RANGE_FRAME_CHICKEN_HENSHIN_SHOT = 1107;
const int CLIPS_CHICKEN_HENSHIN_SHOT[FRAMES_CHICKEN_HENSHIN_SHOT][4] = {
    {RANGE_FRAME_CHICKEN_HENSHIN_SHOT, CHICKEN_0, CHICKEN_W, CHICKEN_H},
    {RANGE_FRAME_CHICKEN_HENSHIN_SHOT, CHICKEN_1, CHICKEN_W, CHICKEN_H},
    {RANGE_FRAME_CHICKEN_HENSHIN_SHOT, CHICKEN_2, CHICKEN_W, CHICKEN_H},
};

const std::string COLLAPSION_BY_CHICKEN_IMG = "../Image/Animation/explosion_chicken.png";
const int FRAMES_COLLAPSION_BY_CHICKEN = 8;
const int COLLAPSION_BY_CHICKEN_W = 224;
const int COLLAPSION_BY_CHICKEN_H = 224;
const int COLLAPSION_BY_CHICKEN_REAL_W = COLLAPSION_BY_CHICKEN_W/COLLAPSION_BY_CHICKEN_SCALE;
const int COLLAPSION_BY_CHICKEN_REAL_H = COLLAPSION_BY_CHICKEN_H/COLLAPSION_BY_CHICKEN_SCALE;
const int RANGE_FRAME_COLLAPSION_BY_CHICKEN = 224;
const int CLIPS_COLLAPSION_BY_CHICKEN[FRAMES_COLLAPSION_BY_CHICKEN][4] = {
    {RANGE_FRAME_COLLAPSION_BY_CHICKEN*0, 0, 224, 224},
    {RANGE_FRAME_COLLAPSION_BY_CHICKEN*1, 0, 224, 224},
    {RANGE_FRAME_COLLAPSION_BY_CHICKEN*2, 0, 224, 224},
    {RANGE_FRAME_COLLAPSION_BY_CHICKEN*3, 0, 224, 224},
    {RANGE_FRAME_COLLAPSION_BY_CHICKEN*4, 0, 224, 224},
    {RANGE_FRAME_COLLAPSION_BY_CHICKEN*5, 0, 224, 224},
    {RANGE_FRAME_COLLAPSION_BY_CHICKEN*6, 0, 224, 224},
    {RANGE_FRAME_COLLAPSION_BY_CHICKEN*7, 0, 224, 224},
};


struct MainBird {

    Animation* bird_ani;
    Mouse* bird_mouse;
    Sprite* bird_spr;

    MainBird();
    MainBird(Animation* bird);
    ~MainBird();

    void init();
    void update();
    void render();
};


struct SupportBird {

    Animation* spbird_ani;
    Animation* flying_ani;
    Animation* gothit_ani;
    Animation* shot_ani;
    Animation* ram_ani;
    Animation* dead_ani;
    Animation* henshin_ani;
    Animation* henshinshot_ani;
    Mouse* spbird_mouse;
    Sprite* spbird_spr;

    SupportBird();
    SupportBird(Animation* _flying_ani, 
                Animation* _gothit_ani, Animation* _shot_ani, 
                Animation* _ram_ani, Animation* _dead_ani, 
                Animation* _henshin_ani, Animation* _henshinshot_ani);
    ~SupportBird();

    void init();
    void update();
    void render();
    void free();

    int health;
    bool alive;
    bool check_alive(int _add);
    void setBird(Animation* ani);
};