#pragma once

#include "Game.h"
#include "Sprite.h"


const std::string DIAMOND_IMG = "../Image/Animation/diamond.png";
const int FLAMES_DIAMOND = 8;
const int DIAMOND_W = 576;
const int DIAMOND_H = 512;
const int DIAMOND_SCALE = 10;
const int DIAMOND_REAL_W = DIAMOND_W/DIAMOND_SCALE;
const int DIAMOND_REAL_H = DIAMOND_H/DIAMOND_SCALE;
const int RANGE_FLAME_DIAMOND = 165+576;
const int CLIPS_DIAMOND[FLAMES_DIAMOND][4] = {
    {70+RANGE_FLAME_DIAMOND*0, 0, 576, 512},
    {70+RANGE_FLAME_DIAMOND*1, 0, 576, 512},
    {70+RANGE_FLAME_DIAMOND*2, 0, 576, 512},
    {70+RANGE_FLAME_DIAMOND*3, 0, 576, 512},
    {70+RANGE_FLAME_DIAMOND*4, 0, 576, 512},
    {70+RANGE_FLAME_DIAMOND*5, 0, 576, 512},
    {70+RANGE_FLAME_DIAMOND*6, 0, 576, 512},
    {70+RANGE_FLAME_DIAMOND*7, 0, 576, 512}
};


const std::string DIAMONDCOLLAPSION_IMG = "../Image/Animation/diamondcollapsion.png";
const int FLAMES_DIAMONDCOLLAPSION = 16;
const int DIAMONDCOLLAPSION_W = 180;
const int DIAMONDCOLLAPSION_H = 180;
const int DIAMONDCOLLAPSION_SCALE = 3;
const int DIAMONDCOLLAPSION_REAL_W = DIAMONDCOLLAPSION_W/DIAMONDCOLLAPSION_SCALE;
const int DIAMONDCOLLAPSION_REAL_H = DIAMONDCOLLAPSION_H/DIAMONDCOLLAPSION_SCALE;
const int RANGE_FLAME_DIAMONDCOLLAPSION = 180;
const int CLIPS_DIAMONDCOLLAPSION[FLAMES_DIAMONDCOLLAPSION][4] = {
    {RANGE_FLAME_DIAMONDCOLLAPSION*0, 0, 180, 180},
    {RANGE_FLAME_DIAMONDCOLLAPSION*1, 0, 180, 180},
    {RANGE_FLAME_DIAMONDCOLLAPSION*2, 0, 180, 180},
    {RANGE_FLAME_DIAMONDCOLLAPSION*3, 0, 180, 180},
    {RANGE_FLAME_DIAMONDCOLLAPSION*4, 0, 180, 180},
    {RANGE_FLAME_DIAMONDCOLLAPSION*5, 0, 180, 180},
    {RANGE_FLAME_DIAMONDCOLLAPSION*6, 0, 180, 180},
    {RANGE_FLAME_DIAMONDCOLLAPSION*7, 0, 180, 180},
    {RANGE_FLAME_DIAMONDCOLLAPSION*8, 0, 180, 180},
    {RANGE_FLAME_DIAMONDCOLLAPSION*9, 0, 180, 180},
    {RANGE_FLAME_DIAMONDCOLLAPSION*10, 0, 180, 180},
    {RANGE_FLAME_DIAMONDCOLLAPSION*11, 0, 180, 180},
    {RANGE_FLAME_DIAMONDCOLLAPSION*12, 0, 180, 180},
    {RANGE_FLAME_DIAMONDCOLLAPSION*13, 0, 180, 180},
    {RANGE_FLAME_DIAMONDCOLLAPSION*14, 0, 180, 180},
    {RANGE_FLAME_DIAMONDCOLLAPSION*15, 0, 180, 180}
};


const std::string 


struct Enemy {

    Enemy() {};

    SDL_Texture *enemy_img;
    SDL_Texture *enemycollaption_img;
    int delay = 0;

    void init();
    void update();
    void update(Pos &pos, int typeOfEnemy);
    void render(int x, int y, int spr, int typeOfEnemy);

    Sprite enemy_spr;
    Sprite enemycollaption_spr;
};